-- Migration: 001_create_schema
-- Description: Canonical schema for VK StreetFood (aligned with current EF model and live Supabase)
-- Notes:
-- - Uses PascalCase table/column names exactly as used by the .NET app.
-- - Includes __EFMigrationsHistory metadata table for EF compatibility.

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "IconUrl" text,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "ColorCode" character varying(7) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "Tours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Emoji" character varying(10) NOT NULL,
    "EstimatedDurationMinutes" integer,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Tours" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "TourTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TourId" integer NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TourTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TourTranslations_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES "Tours" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "PointsOfInterest" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Address" character varying(500) NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CategoryId" integer,
    "AverageRating" numeric(3,2) NOT NULL,
    "TotalRatings" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PointsOfInterest" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointsOfInterest_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
);


CREATE TABLE IF NOT EXISTS "PointOfInterestTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PointOfInterestId" integer NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Address" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PointOfInterestTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointOfInterestTranslations_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "AudioContents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PointOfInterestId" integer NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "TextContent" character varying(2000) NOT NULL,
    "AudioFileUrl" character varying(500),
    "IsGenerated" boolean NOT NULL,
    "DurationSeconds" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_AudioContents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AudioContents_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "PointOfInterestTag" (
    "PointsOfInterestId" integer NOT NULL,
    "TagsId" integer NOT NULL,
    CONSTRAINT "PK_PointOfInterestTag" PRIMARY KEY ("PointsOfInterestId", "TagsId"),
    CONSTRAINT "FK_PointOfInterestTag_PointsOfInterest_PointsOfInterestId" FOREIGN KEY ("PointsOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PointOfInterestTag_Tags_TagsId" FOREIGN KEY ("TagsId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "TourPointsOfInterest" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TourId" integer NOT NULL,
    "PointOfInterestId" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_TourPointsOfInterest" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TourPointsOfInterest_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TourPointsOfInterest_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES "Tours" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Vendors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ContactPerson" character varying(100) NOT NULL,
    "PhoneNumber" character varying(15) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "PointOfInterestId" integer NOT NULL,
    "AverageRating" numeric(3,2) NOT NULL,
    "TotalReviews" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vendors_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "OpeningHours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "OpenTime" interval NOT NULL,
    "CloseTime" interval NOT NULL,
    "IsClosed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_OpeningHours" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpeningHours_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "ImageUrl" text,
    "IsAvailable" boolean NOT NULL,
    "VendorId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(100) NOT NULL,
    "FullName" character varying(100),
    "AvatarUrl" character varying(500),
    "Role" character varying(20) NOT NULL,
    "PasswordHash" character varying(500),
    "IsVerified" boolean NOT NULL,
    "VendorId" integer,
    "LastLoginAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "PoiContentChangeRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OwnerUserId" integer NOT NULL,
    "VendorId" integer NOT NULL,
    "PointOfInterestId" integer NOT NULL,
    "RequestType" character varying(20) NOT NULL,
    "ActionType" character varying(20) NOT NULL,
    "AudioContentId" integer,
    "LanguageCode" character varying(10) NOT NULL,
    "TextContent" character varying(2000) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ReviewedByUserId" integer,
    "ReviewedAt" timestamp with time zone,
    "ReviewNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PoiContentChangeRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PoiContentChangeRequests_AudioContents_AudioContentId" FOREIGN KEY ("AudioContentId") REFERENCES "AudioContents" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PoiContentChangeRequests_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PoiContentChangeRequests_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PoiContentChangeRequests_Users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PoiContentChangeRequests_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "PoiOwnerRegistrations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PointOfInterestId" integer,
    "VendorId" integer,
    "ShopName" character varying(200) NOT NULL,
    "ShopAddress" character varying(500),
    "ContactPhone" character varying(15),
    "Notes" character varying(1000),
    "Status" character varying(20) NOT NULL,
    "ReviewedByUserId" integer,
    "ReviewedAt" timestamp with time zone,
    "ReviewNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PoiOwnerRegistrations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PoiOwnerRegistrations_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PoiOwnerRegistrations_Users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PoiOwnerRegistrations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PoiOwnerRegistrations_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Tourists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviceId" character varying(100) NOT NULL,
    "PreferredLanguage" character varying(10) NOT NULL,
    "LastLatitude" double precision,
    "LastLongitude" double precision,
    "LastLocationUpdate" timestamp with time zone,
    "TotalVisits" integer NOT NULL,
    "UserId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Tourists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tourists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);


CREATE TABLE IF NOT EXISTS "Analytics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PointOfInterestId" integer NOT NULL,
    "TouristId" integer,
    "EventType" character varying(50) NOT NULL,
    "LanguageCode" character varying(10),
    "DurationSeconds" integer,
    "EventTimestamp" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Analytics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Analytics_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Analytics_Tourists_TouristId" FOREIGN KEY ("TouristId") REFERENCES "Tourists" ("Id")
);


CREATE TABLE IF NOT EXISTS "Favorites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" integer NOT NULL,
    "PointOfInterestId" integer NOT NULL,
    "Note" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Favorites_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Favorites_Tourists_TouristId" FOREIGN KEY ("TouristId") REFERENCES "Tourists" ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Ratings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PointOfInterestId" integer NOT NULL,
    "TouristId" integer,
    "Score" integer NOT NULL,
    "Comment" character varying(1000),
    "LanguageCode" character varying(10),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ratings_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Ratings_Tourists_TouristId" FOREIGN KEY ("TouristId") REFERENCES "Tourists" ("Id")
);


CREATE TABLE IF NOT EXISTS "VisitLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" integer NOT NULL,
    "PointOfInterestId" integer NOT NULL,
    "VisitedAt" timestamp with time zone NOT NULL,
    "VisitorLatitude" double precision NOT NULL,
    "VisitorLongitude" double precision NOT NULL,
    "LanguageUsed" character varying(10) NOT NULL,
    "AudioPlayed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_VisitLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VisitLogs_PointsOfInterest_PointOfInterestId" FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VisitLogs_Tourists_TouristId" FOREIGN KEY ("TouristId") REFERENCES "Tourists" ("Id") ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS "IX_Analytics_PointOfInterestId_EventTimestamp" ON "Analytics" ("PointOfInterestId", "EventTimestamp");


CREATE INDEX IF NOT EXISTS "IX_Analytics_TouristId" ON "Analytics" ("TouristId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_AudioContents_PointOfInterestId_LanguageCode" ON "AudioContents" ("PointOfInterestId", "LanguageCode");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_Name" ON "Categories" ("Name");


CREATE INDEX IF NOT EXISTS "IX_Favorites_PointOfInterestId" ON "Favorites" ("PointOfInterestId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_Favorites_TouristId_PointOfInterestId" ON "Favorites" ("TouristId", "PointOfInterestId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_OpeningHours_VendorId_DayOfWeek" ON "OpeningHours" ("VendorId", "DayOfWeek");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_AudioContentId" ON "PoiContentChangeRequests" ("AudioContentId");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_OwnerUserId" ON "PoiContentChangeRequests" ("OwnerUserId");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_PointOfInterestId" ON "PoiContentChangeRequests" ("PointOfInterestId");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_ReviewedByUserId" ON "PoiContentChangeRequests" ("ReviewedByUserId");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_Status" ON "PoiContentChangeRequests" ("Status");


CREATE INDEX IF NOT EXISTS "IX_PoiContentChangeRequests_VendorId" ON "PoiContentChangeRequests" ("VendorId");


CREATE INDEX IF NOT EXISTS "IX_PointOfInterestTag_TagsId" ON "PointOfInterestTag" ("TagsId");


CREATE INDEX IF NOT EXISTS "IX_PointsOfInterest_CategoryId" ON "PointsOfInterest" ("CategoryId");


CREATE INDEX IF NOT EXISTS "IX_PoiOwnerRegistrations_PointOfInterestId" ON "PoiOwnerRegistrations" ("PointOfInterestId");


CREATE INDEX IF NOT EXISTS "IX_PoiOwnerRegistrations_ReviewedByUserId" ON "PoiOwnerRegistrations" ("ReviewedByUserId");


CREATE INDEX IF NOT EXISTS "IX_PoiOwnerRegistrations_Status" ON "PoiOwnerRegistrations" ("Status");


CREATE INDEX IF NOT EXISTS "IX_PoiOwnerRegistrations_UserId" ON "PoiOwnerRegistrations" ("UserId");


CREATE INDEX IF NOT EXISTS "IX_PoiOwnerRegistrations_VendorId" ON "PoiOwnerRegistrations" ("VendorId");


CREATE INDEX IF NOT EXISTS "IX_Products_VendorId" ON "Products" ("VendorId");


CREATE INDEX IF NOT EXISTS "IX_Ratings_PointOfInterestId_TouristId" ON "Ratings" ("PointOfInterestId", "TouristId");


CREATE INDEX IF NOT EXISTS "IX_Ratings_TouristId" ON "Ratings" ("TouristId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tags_Name" ON "Tags" ("Name");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tourists_DeviceId" ON "Tourists" ("DeviceId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_TourTranslations_TourId_LanguageCode" ON "TourTranslations" ("TourId", "LanguageCode");


CREATE INDEX IF NOT EXISTS "IX_Tourists_UserId" ON "Tourists" ("UserId");


CREATE INDEX IF NOT EXISTS "IX_TourPointsOfInterest_PointOfInterestId" ON "TourPointsOfInterest" ("PointOfInterestId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_TourPointsOfInterest_TourId_PointOfInterestId" ON "TourPointsOfInterest" ("TourId", "PointOfInterestId");


CREATE INDEX IF NOT EXISTS "IX_TourPointsOfInterest_TourId_SortOrder" ON "TourPointsOfInterest" ("TourId", "SortOrder");


CREATE INDEX IF NOT EXISTS "IX_Tours_Name" ON "Tours" ("Name");


CREATE INDEX IF NOT EXISTS "IX_Tours_Status" ON "Tours" ("Status");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX IF NOT EXISTS "IX_Users_VendorId" ON "Users" ("VendorId");


CREATE INDEX IF NOT EXISTS "IX_Vendors_PointOfInterestId" ON "Vendors" ("PointOfInterestId");


CREATE INDEX IF NOT EXISTS "IX_VisitLogs_PointOfInterestId" ON "VisitLogs" ("PointOfInterestId");


CREATE INDEX IF NOT EXISTS "IX_VisitLogs_TouristId" ON "VisitLogs" ("TouristId");


-- Runtime-compatible defaults used by owner workflow tables
ALTER TABLE "PoiContentChangeRequests"
    ALTER COLUMN "Status" SET DEFAULT 'pending',
    ALTER COLUMN "CreatedAt" SET DEFAULT NOW(),
    ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;

ALTER TABLE "PoiOwnerRegistrations"
    ALTER COLUMN "Status" SET DEFAULT 'pending',
    ALTER COLUMN "CreatedAt" SET DEFAULT NOW(),
    ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;


-- Keep EF migration metadata in sync for environments initialized via SQL
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224144649_InitialCreateWithIntIds', '10.0.3')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224151409_AddTouristTotalVisitsAndVisitLogDuration', '10.0.3')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305145533_DropQRCodeAndCleanup', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260316134007_AddAudioFileUrlAndDuration', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325012431_AddTourAndTourPointOfInterest', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325022649_SyncTourModelAfterWebCrud', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;



