using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VK.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddOwnerAuthSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // All operations use IF NOT EXISTS / IF NOT EXISTS variants to be fully idempotent.
            // This handles the case where a partial run created tables but the migration
            // was not recorded in __EFMigrationsHistory (e.g., due to concurrent startup on Render).

            // Drop Products table only if it exists.
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Products\" CASCADE;");

            // Create PointOfInterestTranslations only if it doesn't exist yet.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""PointOfInterestTranslations"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PointOfInterestId"" integer NOT NULL,
                    ""LanguageCode"" character varying(10) NOT NULL,
                    ""Name"" character varying(200) NOT NULL,
                    ""Description"" character varying(1000) NOT NULL,
                    ""Address"" character varying(500) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    ""IsDeleted"" boolean NOT NULL,
                    ""DeletedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_PointOfInterestTranslations"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_PointOfInterestTranslations_PointsOfInterest_PointOfInteres~""
                        FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest"" (""Id"") ON DELETE CASCADE
                );");

            // Create QrPaymentConfigs only if it doesn't exist yet.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""QrPaymentConfigs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""DefaultAmountVnd"" numeric(12,0) NOT NULL DEFAULT 0,
                    ""DeepLinkName"" character varying(50) NOT NULL DEFAULT 'pay',
                    ""QrTtlMinutes"" integer NOT NULL DEFAULT 15,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    ""IsDeleted"" boolean NOT NULL,
                    ""DeletedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_QrPaymentConfigs"" PRIMARY KEY (""Id"")
                );");

            // Create TourTranslations only if it doesn't exist yet.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TourTranslations"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""TourId"" integer NOT NULL,
                    ""LanguageCode"" character varying(10) NOT NULL,
                    ""Name"" character varying(200) NOT NULL,
                    ""Description"" character varying(1000) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    ""IsDeleted"" boolean NOT NULL,
                    ""DeletedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_TourTranslations"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TourTranslations_Tours_TourId""
                        FOREIGN KEY (""TourId"") REFERENCES ""Tours"" (""Id"") ON DELETE CASCADE
                );");

            // Create indices only if they don't exist yet.
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PointOfInterestTranslations_PointOfInterestId_LanguageCode""
                ON ""PointOfInterestTranslations"" (""PointOfInterestId"", ""LanguageCode"");");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_TourTranslations_TourId_LanguageCode""
                ON ""TourTranslations"" (""TourId"", ""LanguageCode"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PointOfInterestTranslations");

            migrationBuilder.DropTable(
                name: "QrPaymentConfigs");

            migrationBuilder.DropTable(
                name: "TourTranslations");

            migrationBuilder.CreateTable(
                name: "Products",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    VendorId = table.Column<int>(type: "integer", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    ImageUrl = table.Column<string>(type: "text", nullable: true),
                    IsAvailable = table.Column<bool>(type: "boolean", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Price = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Products", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Products_Vendors_VendorId",
                        column: x => x.VendorId,
                        principalTable: "Vendors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Products_VendorId",
                table: "Products",
                column: "VendorId");
        }
    }
}
