using VK.Infrastructure.Data;
using VK.Infrastructure.Seeds;
using Microsoft.EntityFrameworkCore;

namespace VK.API.Extensions;

public static class DatabaseExtensions
{
    public static async Task EnsureOwnerAuthSchemaAsync(this WebApplication app)
    {
        try
        {
            using var scope = app.Services.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<VKStreetFoodDbContext>();

            var sql = @"
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""PasswordHash"" character varying(500);
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""IsVerified"" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS ""PoiOwnerRegistrations"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""UserId"" integer NOT NULL,
    ""PointOfInterestId"" integer NULL,
    ""VendorId"" integer NULL,
    ""ShopName"" character varying(200) NOT NULL,
    ""ShopAddress"" character varying(500) NULL,
    ""ContactPhone"" character varying(15) NULL,
    ""Notes"" character varying(1000) NULL,
    ""Status"" character varying(20) NOT NULL DEFAULT 'pending',
    ""ReviewedByUserId"" integer NULL,
    ""ReviewedAt"" timestamp with time zone NULL,
    ""ReviewNote"" character varying(500) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedAt"" timestamp with time zone NULL,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    ""DeletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Users_ReviewedByUserId"" FOREIGN KEY (""ReviewedByUserId"") REFERENCES ""Users""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_PointsOfInterest_PointOfInterestId"" FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Vendors_VendorId"" FOREIGN KEY (""VendorId"") REFERENCES ""Vendors""(""Id"") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ""IX_PoiOwnerRegistrations_Status"" ON ""PoiOwnerRegistrations"" (""Status"");

CREATE TABLE IF NOT EXISTS ""PoiContentChangeRequests"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""OwnerUserId"" integer NOT NULL,
    ""VendorId"" integer NOT NULL,
    ""PointOfInterestId"" integer NOT NULL,
    ""RequestType"" character varying(20) NOT NULL,
    ""ActionType"" character varying(20) NOT NULL,
    ""AudioContentId"" integer NULL,
    ""LanguageCode"" character varying(10) NOT NULL,
    ""TextContent"" character varying(2000) NOT NULL,
    ""Status"" character varying(20) NOT NULL DEFAULT 'pending',
    ""ReviewedByUserId"" integer NULL,
    ""ReviewedAt"" timestamp with time zone NULL,
    ""ReviewNote"" character varying(500) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedAt"" timestamp with time zone NULL,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    ""DeletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""FK_PoiContentChangeRequests_Users_OwnerUserId"" FOREIGN KEY (""OwnerUserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_Users_ReviewedByUserId"" FOREIGN KEY (""ReviewedByUserId"") REFERENCES ""Users""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiContentChangeRequests_Vendors_VendorId"" FOREIGN KEY (""VendorId"") REFERENCES ""Vendors""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_PointsOfInterest_PointOfInterestId"" FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_AudioContents_AudioContentId"" FOREIGN KEY (""AudioContentId"") REFERENCES ""AudioContents""(""Id"") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_Status"" ON ""PoiContentChangeRequests"" (""Status"");
CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_OwnerUserId"" ON ""PoiContentChangeRequests"" (""OwnerUserId"");
CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_PointOfInterestId"" ON ""PoiContentChangeRequests"" (""PointOfInterestId"");

CREATE TABLE IF NOT EXISTS ""PointOfInterestTranslations"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PointOfInterestId"" integer NOT NULL,
    ""LanguageCode"" character varying(10) NOT NULL,
    ""Name"" character varying(200) NOT NULL,
    ""Description"" character varying(1000) NOT NULL DEFAULT '',
    ""Address"" character varying(500) NOT NULL DEFAULT '',
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedAt"" timestamp with time zone NULL,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    ""DeletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""FK_PointOfInterestTranslations_PointsOfInterest_PointOfInterestId""
        FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest""(""Id"") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PointOfInterestTranslations_PoiLang""
    ON ""PointOfInterestTranslations"" (""PointOfInterestId"", ""LanguageCode"");

INSERT INTO ""PointOfInterestTranslations""
    (""PointOfInterestId"", ""LanguageCode"", ""Name"", ""Description"", ""Address"", ""CreatedAt"", ""IsDeleted"")
SELECT p.""Id"", 'vi', p.""Name"", p.""Description"", p.""Address"", NOW(), false
FROM ""PointsOfInterest"" p
LEFT JOIN ""PointOfInterestTranslations"" t
    ON t.""PointOfInterestId"" = p.""Id"" AND t.""LanguageCode"" = 'vi'
WHERE t.""Id"" IS NULL;
";

            await context.Database.ExecuteSqlRawAsync(sql);
        }
        catch (Exception ex)
        {
            var logger = app.Services.GetRequiredService<ILogger<WebApplication>>();
            logger.LogWarning(ex, "Owner auth schema bootstrap skipped in API.");
        }
    }

    public static async Task SeedDatabaseAsync(this WebApplication app)
    {
        try
        {
            using var scope = app.Services.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<VKStreetFoodDbContext>();
            await DatabaseSeeder.SeedAsync(context);
        }
        catch (Exception ex)
        {
            var logger = app.Services.GetRequiredService<ILogger<WebApplication>>();
            logger.LogWarning(ex, "Database seeding skipped (DB unreachable). Server will still start.");
        }
    }

    /// <summary>
    /// Fire-and-forget seeding — does NOT block startup.
    /// Runs after a short delay so the server is already listening.
    /// </summary>
    public static WebApplication SeedDatabaseInBackground(this WebApplication app)
    {
        _ = Task.Run(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(2)); // let server start first
            try
            {
                using var scope = app.Services.CreateScope();
                var context = scope.ServiceProvider.GetRequiredService<VKStreetFoodDbContext>();
                await DatabaseSeeder.SeedAsync(context);
            }
            catch (Exception ex)
            {
                var logger = app.Services.GetRequiredService<ILogger<WebApplication>>();
                logger.LogWarning(ex, "Background seeding skipped (DB unreachable).");
            }
        });
        return app;
    }
}