using Microsoft.EntityFrameworkCore;
using VK.Infrastructure.Data;

namespace VK.Web.Services;

public static class SchemaBootstrapper
{
    public static async Task EnsureOwnerAuthSchemaAsync(IServiceProvider services, ILogger logger)
    {
        try
        {
            using var scope = services.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<VKStreetFoodDbContext>();

            var sql = @"
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""PasswordHash"" character varying(500);
ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""IsVerified"" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS ""PoiOwnerRegistrations"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""UserId"" integer NOT NULL,
    ""PointOfInterestId"" integer NULL,
    ""VendorId"" integer NULL,
    ""ShopName"" character varying(200) NOT NULL,
    ""ShopAddress"" character varying(500) NULL,
    ""ContactPhone"" character varying(15) NULL,
    ""Notes"" character varying(1000) NULL,
    ""Status"" character varying(20) NOT NULL DEFAULT 'pending',
    ""ReviewedByUserId"" integer NULL,
    ""ReviewedAt"" timestamp with time zone NULL,
    ""ReviewNote"" character varying(500) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedAt"" timestamp with time zone NULL,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    ""DeletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Users_ReviewedByUserId"" FOREIGN KEY (""ReviewedByUserId"") REFERENCES ""Users""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_PointsOfInterest_PointOfInterestId"" FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiOwnerRegistrations_Vendors_VendorId"" FOREIGN KEY (""VendorId"") REFERENCES ""Vendors""(""Id"") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ""IX_PoiOwnerRegistrations_Status"" ON ""PoiOwnerRegistrations"" (""Status"");

CREATE TABLE IF NOT EXISTS ""PoiContentChangeRequests"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""OwnerUserId"" integer NOT NULL,
    ""VendorId"" integer NOT NULL,
    ""PointOfInterestId"" integer NOT NULL,
    ""RequestType"" character varying(20) NOT NULL,
    ""ActionType"" character varying(20) NOT NULL,
    ""AudioContentId"" integer NULL,
    ""LanguageCode"" character varying(10) NOT NULL,
    ""TextContent"" character varying(2000) NOT NULL,
    ""Status"" character varying(20) NOT NULL DEFAULT 'pending',
    ""ReviewedByUserId"" integer NULL,
    ""ReviewedAt"" timestamp with time zone NULL,
    ""ReviewNote"" character varying(500) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedAt"" timestamp with time zone NULL,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    ""DeletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""FK_PoiContentChangeRequests_Users_OwnerUserId"" FOREIGN KEY (""OwnerUserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_Users_ReviewedByUserId"" FOREIGN KEY (""ReviewedByUserId"") REFERENCES ""Users""(""Id"") ON DELETE SET NULL,
    CONSTRAINT ""FK_PoiContentChangeRequests_Vendors_VendorId"" FOREIGN KEY (""VendorId"") REFERENCES ""Vendors""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_PointsOfInterest_PointOfInterestId"" FOREIGN KEY (""PointOfInterestId"") REFERENCES ""PointsOfInterest""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PoiContentChangeRequests_AudioContents_AudioContentId"" FOREIGN KEY (""AudioContentId"") REFERENCES ""AudioContents""(""Id"") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_Status"" ON ""PoiContentChangeRequests"" (""Status"");
CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_OwnerUserId"" ON ""PoiContentChangeRequests"" (""OwnerUserId"");
CREATE INDEX IF NOT EXISTS ""IX_PoiContentChangeRequests_PointOfInterestId"" ON ""PoiContentChangeRequests"" (""PointOfInterestId"");
";

            await context.Database.ExecuteSqlRawAsync(sql);
            logger.LogInformation("Owner auth schema bootstrap completed.");
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Owner auth schema bootstrap skipped.");
        }
    }
}
