CREATE TABLE IF NOT EXISTS "QrPaymentConfigs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DefaultAmountVnd" numeric(12,0) NOT NULL DEFAULT 0,
    "DeepLinkName" character varying(50) NOT NULL DEFAULT 'pay',
    "QrTtlMinutes" integer NOT NULL DEFAULT 15,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL
);

INSERT INTO "QrPaymentConfigs" ("DefaultAmountVnd", "DeepLinkName", "QrTtlMinutes")
SELECT 0, 'pay', 15
WHERE NOT EXISTS (SELECT 1 FROM "QrPaymentConfigs" WHERE "IsDeleted" = FALSE);
