-- Migration: add multilingual fields for POI text content
-- Creates PointOfInterestTranslations and backfills Vietnamese baseline rows.

CREATE TABLE IF NOT EXISTS "PointOfInterestTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PointOfInterestId" integer NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL DEFAULT '',
    "Address" character varying(500) NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PointOfInterestTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PointOfInterestTranslations_PointsOfInterest_PointOfInterestId"
        FOREIGN KEY ("PointOfInterestId") REFERENCES "PointsOfInterest" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PointOfInterestTranslations_PointOfInterestId_LanguageCode"
    ON "PointOfInterestTranslations" ("PointOfInterestId", "LanguageCode");

CREATE INDEX IF NOT EXISTS "IX_PointOfInterestTranslations_PointOfInterestId"
    ON "PointOfInterestTranslations" ("PointOfInterestId");

INSERT INTO "PointOfInterestTranslations"
    ("PointOfInterestId", "LanguageCode", "Name", "Description", "Address", "CreatedAt", "IsDeleted")
SELECT
    p."Id",
    'vi',
    p."Name",
    p."Description",
    p."Address",
    NOW(),
    FALSE
FROM "PointsOfInterest" p
LEFT JOIN "PointOfInterestTranslations" t
    ON t."PointOfInterestId" = p."Id" AND t."LanguageCode" = 'vi'
WHERE t."Id" IS NULL;
